from typing import Any, Protocol

class NMEAMessage(Protocol):
    identity: str
    talker: str
    msgID: str
    def serialize(self) -> bytes: ...

class NMEAReader:
    def __init__(self, stream: Any, **kwargs: Any) -> None: ...
    def read(self) -> tuple[bytes, NMEAMessage | None]: ...
    @staticmethod
    def parse(data: bytes) -> NMEAMessage: ...
