# typings/pyubx2/__init__.pyi
from typing import Any

class UBXMessage:
    identity: str
    clsID: int | None
    msgID: int | None

    def __init__(self, msgClass: Any, msgID: Any, *args: Any, **kwargs: Any) -> None: ...
    def serialize(self) -> bytes: ...

class UBXReader:
    def __init__(self, stream: Any, **kwargs: Any) -> None: ...
    def read(self) -> tuple[bytes, UBXMessage | None]: ...
    @staticmethod
    def parse(data: bytes) -> UBXMessage: ...
